use_frameworks!
platform :ios, '8.0'
target 'Vipr_Tests' do
  pod 'Vipr', :path => '../'
  
  pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.3'
  
  pod 'Alamofire', '~> 4.6.0'
  pod 'SwiftyJSON', '~> 4.0.0'
  
  # pod 'Mixpanel-swift'
end
